
version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dbescolar'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'estuda.com'
      # You can use whatever password you like
      MYSQL_PASSWORD: '0121@Estudar'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
      


# version: '3.3'

# services:

#   db:
#     container_name: "db_mysql_escolar"
#     image: mysql:5.7
#     restart: always
#     # ports:
#     #   - '3306:3306'
#     environment: 
#       MYSQL_ROOT_PASSWORD: '123@Escola'
    
#     # volumes:
#     #   -  ./.docker/mysql/data:/var/lib/mysql
#     networks:
#       - mysql-compose-network
 
 
 
# networks: 
#   mysql-compose-network:
#     driver: bridge

     